### PR TITLE
add enableJwt checkbox to create room page #11

### PR DESCRIPTION
**Pull request by fae7em**

### CODE REVIEW

**Comment by luke-** [comment]
Some notes:

- Since the values in the red box are only related to the JWT authentication, we should hide them, when the new checkbox is not activated.
image

- The translation files are usually generated automatically by us, but that's ok for this PR.

- I've also added a commit which may fixes the key problem (if I understood correctly) 

- Maybe we should also add model rules which makes appId & appSecret required when JWT is enabled 
https://github.com/fae7em/jitsi-meet/blob/feature/enableJwtCheckbox/models/SettingsForm.php#L26

**Review by luke- — CHANGES_REQUESTED** [review]
See comment above

**Comment by fae7em** [comment]
About the first note, as I understand the jitsi-meet/room/open endpoint is used to create a room, and each time we want to create a room we can choose the jwt enable state, so it's not a constant and general setting for all rooms but the AppId and AppSecret are some general settings for this module, so we shouldn't change them each time (and also we shouldn't hide them) unless we move "enable jwt authentication" to module setting part and make it a general setting for all rooms. in this case, we can implement the first note and if we don't make it a general setting then we can implement the forth note you mentioned.

**Comment by luke-** [comment]
@fae7em I don't have a JWT Jitsi Server running myself, but the AppID&AppSecret should only used to create JWT tokens. I don't think JWT is a "per room" setting, more a glboal Jitsi server / HUmHub module setting.

**Comment by fae7em** [comment]
You're right, So I'll move it to the module setting.

**Comment by markushagge** [comment]
@luke @fae7em In fact, it's a per Jits-server setting

**Review by luke- — APPROVED** [review]

**Pull request merged**
